### ISSUE TITLE
告知タスク

### ISSUE THREAD

**Issue by omuomugin** [MentorsSchool/CodingTrip#1]
## ToDo
- [x] 告知文の作成
- [x] 告知文のブラッシュアップ
- [ ] イベント内容の決定とブラッシュアップ
- [x] イベント登録フォームの作成
- [ ] 告知用のイメージの作成

**Comment by omuomugin** [comment]
## 告知文[ver 3.0]

告知文

みなさん、キャンプもB日程が終わり、やっと夏の折り返し地点ですね！
そんなみなさんに、キャンプ終了後の9月に予定している激アツな合宿のご案内です！！

その名も、CodingTripです！
この合宿は、自分の好きなコードを好きなだけ書くイベントになっています！
作りたいと作りたいと思っていたあの作品、『忙しくて手を付けられていない』なんてことありませんか？CodingTripは、絶好の環境でそんな普段なかなか書けなかったコードを書くイベントになっています。
当然、わからないことや協力が欲しいときは最高の仲間がいるので、頼ってOKです！

参加方法は、以下のフォームから情報を入力するだけです！ただし、参加者が多くなりすぎた場合などを考慮して簡単な問題を定めさせていただいております。
こちら、円滑な運営のためにご協力いただければと思います！

**Comment by Aguri** [comment]
たたき台
![codingtrip](https://cloud.githubusercontent.com/assets/7918776/16513353/01c73cb6-3f9f-11e6-9fe1-b4aec79b70c7.png)

**Comment by omuomugin** [comment]
coding tripはメンターズスクールのイベントというよりも、LiTUniversityのイベントになる予定。
それに合わせて、告知文のブラッシュアップをする

**Comment by omuomugin** [comment]
<参加登録フォーム>
https://docs.google.com/forms/d/e/1FAIpQLSedLlU4AlSLRO678HzU-JY55dcKl0qyOzU_Le_jAedz8FsvHQ/viewform

<コーディングテストのリンク>

https://docs.google.com/forms/d/e/1FAIpQLSf2ARgjAnXBJys--ONLQLCgb6EBLKX2MHxE4q4JaFOPeS-LlQ/viewform

**Comment by Aguri** [comment]
![codingtrip](https://cloud.githubusercontent.com/assets/7918776/17810256/0257cbc6-6657-11e6-9b77-01b1605a64a2.png)

**Comment by Aguri** [comment]
告知用画像つくりました！
